name: capstone_bus_manage
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    get: ^4.7.2
    http: ^1.4.0
    get_storage: ^2.1.1
    intl: ^0.20.2
    shared_preferences: ^2.5.3
    cupertino_icons: ^1.0.8
    # giffy_dialog: ^2.3.0
    lottie: ^2.2.0
    # awesome_dialog: ^3.2.1
    persistent_bottom_nav_bar: any
    flutter_svg: 2.1.0
    google_mlkit_face_detection: ^0.13.1
    tflite_flutter: ^0.11.0
    camera: ^0.10.4
    image: ^4.0.17
    google_sign_in: ^6.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    flutter_launcher_icons: ^0.14.3

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icons/apk-icon.png"

flutter:
    uses-material-design: true
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700
    assets:
        - assets/icons/
        - assets/icons/active/
        - assets/icons/non_active/
        #
        #
        - assets/images/
        - assets/models/
        - assets/labels/
        - assets/animations/
